(require 'region-bindings-mode)
(require 'multiple-cursors)
(require 'which-key)
(require 'expand-region)

(region-bindings-mode-enable)

(defun my/which-key-region-bindings ()
  (interactive)
  (which-key--show-keymap
   "Region Bindings"
   region-bindings-mode-map))

(bind-keys :map region-bindings-mode-map
           (";" . my/comment-line-or-region)
           ("?" . my/which-key-region-bindings)
           ("A" . beginning-of-buffer)
           ("B" . backward-sexp)
           ("C" . my/kill-line-or-region)
           ("D" . er/mark-defun)
           ("E" . end-of-buffer)
           ("F" . forward-sexp)
           ("G" . my/google-search)
           ("J" . ace-jump-word-mode)
           ("L" . mc/edit-lines)
           ("N" . mc/skip-to-next-like-this)
           ("S" . sort-lines)
           ("SPC" . exchange-point-and-mark)
           ("a" . beginning-of-line)
           ("b" . backward-word)
           ("c" . my/copy-line-or-region)
           ("d" . my/duplicate-line-or-region)
           ("e" . end-of-line)
           ("f" . forward-word)
           ("i" . indent-rigidly)
           ("j" . next-line)
           ("k" . my/region-bindings-k)
           ("l" . my/select-line)
           ("m" . vr/mc-mark)
           ("n" . mc/mark-next-like-this)
           ("q" . er/mark-inside-quotes)
           ("r" . er/expand-region)
           ("s" . my/isearch-region)
           ("u" . er/mark-url)
           ("w" . my/select-word)
           ;; ("L" . ace-jump-line-mode)
           ;; By default, TAB does indent-region
           )

(defun my/region-bindings-k ()
  (interactive)
  (if (eq major-mode 'magit-status-mode)
      (magit-discard)
    (previous-line)))

(add-to-list 'region-bindings-mode-disable-predicates
             'minibufferp)
;; (global-set-key (kbd "C-i") 'calendar)
;; (global-set-key (kbd "<tab>") 'beginning-of-line)
