(require 'region-bindings-mode)
(require 'multiple-cursors)

(region-bindings-mode-enable)

(bind-keys :map region-bindings-mode-map
           (";" . my/comment-line-or-region)
           ("A" . beginning-of-buffer)
           ("B" . backward-sexp)
           ("C" . kill-region)
           ("D" . er/mark-defun)
           ("E" . end-of-buffer)
           ("E" . er/mark-email)
           ("F" . forward-sexp)
           ("J" . ace-jump-word-mode)
           ("L" . ace-jump-line-mode)
           ("M" . mc/edit-lines)
           ("S" . sort-lines)
           ("SPC" . exchange-point-and-mark)
           ("a" . beginning-of-line)
           ("b" . backward-word)
           ("c" . kill-ring-save)
           ("d" . my/duplicate-line-or-region)
           ("e" . end-of-line)
           ("f" . forward-word)
           ("j" . next-line)
           ("k" . my/region-bindings-k)
           ("l" . my/select-line)

           ("m" . vr/mc-mark)
           ("n" . mc/mark-next-like-this)
           (">" . mc/skip-to-next-like-this)
           ("<" . mc/skip-to-previous-like-this)
           ("r" . er/expand-region)
           ("u" . er/mark-url)
           ("w" . my/select-word)
           )

(defun my/region-bindings-k ()
  (interactive)
  (if (eq major-mode 'magit-status-mode)
      (magit-discard)
    (previous-line)))

(add-to-list 'region-bindings-mode-disable-predicates
             'minibufferp)
;; (global-set-key (kbd "C-i") 'calendar)
;; (global-set-key (kbd "<tab>") 'beginning-of-line)
