# -*- mode: sh -*-
. ~/my/dotfiles/bash/git-completion.bash
. ~/my/dotfiles/bash/git-prompt.sh

export PATH=~/my/dotfiles/bin:~/go/bin:$PATH
if [ -e /Applications/Emacs.app/Contents/MacOS/bin ];
then
    export PATH=/Applications/Emacs.app/Contents/MacOS/bin:$PATH
fi

export GOPATH=~/go

if [ "$(uname)" = "Darwin" ]; then
  export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
  export MANPATH=/usr/local/opt/coreutils/libexec/gnuman:$MANPATH
fi

export LESS='-r -i-P%f (%i/%m) Line %lt/%L'
export EDITOR=emacsclient
export VISUAL=emacsclient

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend
# Number of lines of ~/.bash_history
HISTSIZE=10000
# Number of commands Bash will keep in memory
HISTFILESIZE=10000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

if [ -e /usr/local/bin/bash ]; then
    export SHELL=/usr/local/bin/bash
fi

if [ -e ~/.bashrc_private ];
then
  . ~/.bashrc_private
fi

export COLOR_BLACK='\e[0;30m'
export COLOR_BLUE='\e[0;34m'
export COLOR_CYAN='\e[0;36m'
export COLOR_GRAY='\e[0;30m'
export COLOR_GREEN='\e[0;32m'
export COLOR_LIGHT_BLUE='\e[1;34m'
export COLOR_LIGHT_CYAN='\e[1;36m'
export COLOR_LIGHT_GRAY='\e[0;37m'
export COLOR_LIGHT_GREEN='\e[1;32m'
export COLOR_LIGHT_PURPLE='\e[1;35m'
export COLOR_LIGHT_RED='\e[1;31m'
export COLOR_NC='\e[0m' # No Color
export COLOR_PURPLE='\e[0;35m'
export COLOR_RED='\e[0;31m'
export COLOR_WHITE='\e[1;37m'
export COLOR_YELLOW='\e[1;33m'

export BG_GRAY='\e[100m'
export UNDERLINE='\e[4m'

__my_prompt_command() {
  local exitcode="$?"
  local gitbranch=$(__git_ps1 "%s")
  local cwd="\w"
  local cwd_expanded=${cwd@P}
  local date="[\D{%Y-%m-%d %I:%M:%S%p}]"

  if [ "$gitbranch" != "" ]
  then
      gitbranch="($gitbranch)"
  fi

  local lhs="$date $cwd_expanded $gitbranch"
  local rhs="$date [$exitcode]"

  local lhs_expanded=${lhs@P}
  local rhs_expanded=${rhs@P}

  local nspaces=$(( COLUMNS - ${#lhs_expanded} - ${#rhs_expanded} ))
  local spaces=$(printf '%*s' $nspaces)

  # Write to ~/.bash_history immediately after each command is typed in.
  history -a

  PS1="$lhs$spaces$rhs\n> "
}

export PROMPT_COMMAND="__my_prompt_command"

. ~/my/dotfiles/bash/aliases

if [ -e /usr/share/autojump/autojump.sh ];
then
    . /usr/share/autojump/autojump.sh
fi

export PYTHONSTARTUP=~/.pythonrc.py
