. ~/my/dotfiles/bash/git-prompt.sh
. ~/my/dotfiles/bash/git-completion.bash

. ~/my/dotfiles/bash/aliases

if [ "$TERM" = "dumb" ]; then
    PS1='\w \$ '
else
    PS1='\w$(__git_ps1)\$ '
fi
export PS1

export PATH=~/my/dotfiles/bin:$PATH

export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
export MANPATH=/usr/local/opt/coreutils/libexec/gnuman:$MANPATH

export LESS='-r -i-P%f (%i/%m) Line %lt/%L'
export EDITOR=emacsclient
export VISUAL=emacsclient

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend
# Number of lines of ~/.bash_history
HISTSIZE=10000
# Number of commands Bash will keep in memory
HISTFILESIZE=10000

# Write to ~/.bash_history immediately after each command is typed in.
export PROMPT_COMMAND='history -a'

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

if [ -e ~/.bashrc_private ];
then
  . ~/.bashrc_private
fi

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
