# -*- mode: sh mode -*-
. ~/my/dotfiles/bash/git-completion.bash
. ~/my/dotfiles/bash/git-prompt.sh

export PATH=~/my/dotfiles/bin:$PATH

if [ "$(uname)" = "Darwin" ]; then
  export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
  export MANPATH=/usr/local/opt/coreutils/libexec/gnuman:$MANPATH
fi

export LESS='-r -i-P%f (%i/%m) Line %lt/%L'
export EDITOR=emacsclient
export VISUAL=emacsclient

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend
# Number of lines of ~/.bash_history
HISTSIZE=10000
# Number of commands Bash will keep in memory
HISTFILESIZE=10000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

if [ -e ~/.bashrc_private ];
then
  . ~/.bashrc_private
fi

export COLOR_BLACK='\e[0;30m'
export COLOR_BLUE='\e[0;34m'
export COLOR_BROWN='\e[0;33m'
export COLOR_CYAN='\e[0;36m'
export COLOR_GRAY='\e[0;30m'
export COLOR_GREEN='\e[0;32m'
export COLOR_LIGHT_BLUE='\e[1;34m'
export COLOR_LIGHT_CYAN='\e[1;36m'
export COLOR_LIGHT_GRAY='\e[0;37m'
export COLOR_LIGHT_GREEN='\e[1;32m'
export COLOR_LIGHT_PURPLE='\e[1;35m'
export COLOR_LIGHT_RED='\e[1;31m'
export COLOR_NC='\e[0m' # No Color
export COLOR_PURPLE='\e[0;35m'
export COLOR_RED='\e[0;31m'
export COLOR_WHITE='\e[1;37m'
export COLOR_YELLOW='\e[1;33m'

export _my_extra_prompt=

my_set_extra_prompt() {
  export _my_extra_prompt=$1
}

__my_prompt_command() {
  local exitcode="$?"
  local gitbranch=$(__git_ps1 "%s")
  local cwd="$COLOR_LIGHT_BLUE\w "

  local whoami=$(whoami)
  local final_prompt="\$"
  local timestamp=""
  local extra=""

  if [ "$_my_extra_prompt" != "" ]
  then
    extra="$_my_extra_prompt "
  fi

  if [ "$whoami" == "root" ]
  then
    whoami="$COLOR_RED$whoami$COLOR_NC"
    final_prompt="#"
  fi
  timestamp="$COLOR_NO<$whoami@\h \D{%F %T}>"

  if [ "$gitbranch" != "" ]
  then
    gitbranch="$COLOR_BROWN($gitbranch) "
  fi

  if [ "$exitcode" != "0" ]
  then
    exitcode="$COLOR_LIGHT_RED[$exitcode]$COLOR_NC "
  else
    exitcode=""
  fi

  # Write to ~/.bash_history immediately after each command is typed in.
  history -a

  PS1="$cwd$gitbranch$COLOR_NC$exitcode$timestamp$COLOR_NC\n$extra$final_prompt "
}

if [ "$PROMPT_COMMAND" == "" ]
then
    export PROMPT_COMMAND="__my_prompt_command"
else
    export PROMPT_COMMAND="__my_prompt_command; $PROMPT_COMMAND"
fi

. ~/my/dotfiles/bash/aliases

export NVM_DIR="/home/dev/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
